name: build

on:
  push:
  schedule:
    - cron: '0 0 * * *'

env:
  # The only way to simulate if-else statement
  CHECKOUT_BRANCH: ${{ github.event_name == 'push' && github.ref || 'develop' }}

jobs:

  check-code-black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.CHECKOUT_BRANCH }}

      - name: Check code compliance with black
        run: |
          pip install black[jupyter]
          black . --check --diff

  check-code-isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.CHECKOUT_BRANCH }}

      - name: Check code compliance with isort
        run: |
          pip install isort
          isort . --check --diff

  test-on-github:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.CHECKOUT_BRANCH }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libopenjp2-7
          pip install -e .[DEV]

      - name: Run full tests and code coverage
        if: matrix.python-version == '3.9'
        run: |
          sentinelhub.config \
            --sh_client_id "${{ secrets.SH_CLIENT_ID }}" \
            --sh_client_secret "${{ secrets.SH_CLIENT_SECRET }}"
          pytest --cov --cov-report=term --cov-report=xml

      - name: Run pylint and reduced tests
        if: matrix.python-version != '3.9'
        run: |
          pylint s2cloudless
          pytest -m "not sh_integration"

      - name: Upload code coverage
        if: matrix.python-version == '3.9'
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          fail_ci_if_error: true
          verbose: false
